### ISSUE TITLE
The games ( sensor placement ) is not working properly

### ISSUE THREAD

**Issue by Sandhya-105** [oer4sdi/spatial-streaming-oer#3]
## Screenshots:
![Screenshot 2022-08-13 153703](https://user-images.githubusercontent.com/94603960/184585195-84e85772-1e96-42fe-acb1-88f07da68c4f.png)

I placed the points as per the guide but still, it is not approving the answers

**Comment by purijs** [comment]
![image](https://user-images.githubusercontent.com/22521404/185793091-f93784de-717e-46f1-aedd-c78de2bdb023.png)
@Sandhya-105 This is the solution to the image. If you click on any of the boxes it'll be correct. Earlier the hotspot regions were small but I've increased the box size to get correct hits, the idea is for the user to "retry" and find all possible boxes. 

Let me know if there's a better way to do this because using H5P that's all I could create
